Solved module 1 (all 5 tasks)
js-tasks-ru/jsbasic-20220901_octa pull request #3
Opened 2022-09-04 19:26 UTC by lingvocoder

2022-09-04 19:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-06 08:44 UTC, SinimaWath requested changes

2022-09-06 08:44 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
Давай упростим без else и без временной переменой:
```
if (str.length <= maxlength) {
  return str;
}

return `${str.substring(0, maxlength - 1)}…`
```

2022-09-06 08:44 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  else if (name === '') {
name === null и name === '' - можно проверить, одним условием `if(!name)`

2022-09-07 18:02 UTC, lingvocoder commented on 1-module/5-task/index.js
> +  }
Так гораздо изящнее

2022-09-07 18:02 UTC, lingvocoder commented on 1-module/2-task/index.js
> +  else if (name === '') {
Действительно)

2022-09-08 14:17 UTC, SinimaWath approved these changes

2022-09-08 14:17 UTC, merged