Solved 3 tasks for module-4
js-tasks-ru/jsbasic-20220901_octa pull request #6
Opened 2022-09-18 13:36 UTC by lingvocoder

2022-09-18 13:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-19 10:20 UTC, SinimaWath requested changes

2022-09-19 10:20 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  }).join('');
Кажется эта функция лишняя, код и так достаточно компактный:
```
list.innerHTML = friends.map(({firstName, lastName}) => `${getListItem({firstName, lastName})}`).join('')
```

2022-09-19 10:20 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  }
Можно за один цикл:
`const td = table.rows[i].cells[i]`

2022-09-19 11:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-19 11:10 UTC, SinimaWath approved these changes

2022-09-19 11:10 UTC, merged